# Generated by Django 3.1.5 on 2021-03-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_app', '0002_auto_20210328_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
