# Generated by Django 3.1.5 on 2021-04-10 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210403_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_high',
            field=models.BigIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_low',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='car_status',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.BigIntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_preference',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maximum_age',
            field=models.BigIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='minimum_age',
            field=models.BigIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_maximum',
            field=models.BigIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_minimum',
            field=models.BigIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
