# Generated by Django 3.1.5 on 2021-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
