# Generated by Django 3.1.7 on 2021-04-18 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210412_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 18)),
        ),
    ]
