# Generated by Django 3.1.7 on 2021-04-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210418_2129'),
        ('users', '0010_auto_20210418_2027'),
    ]

    operations = [
    ]
