# Generated by Django 3.1.6 on 2021-04-19 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210418_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 19)),
        ),
    ]
