# Generated by Django 3.1.7 on 2021-04-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210419_1258'),
        ('users', '0011_merge_20210419_1728'),
    ]

    operations = [
    ]
