# Generated by Django 3.1.6 on 2021-04-26 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210420_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.BigIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level',
            field=models.BigIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 26)),
        ),
    ]
