# Generated by Django 3.1.6 on 2021-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210426_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation_year_preference',
            field=models.BigIntegerField(default=2023),
        ),
    ]
