# Generated by Django 3.1.5 on 2021-04-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_graduation_year_preference'),
        ('users', '0014_auto_20210425_2243'),
    ]

    operations = [
    ]
