# Generated by Django 3.1.5 on 2021-04-28 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210427_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 28)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.BigIntegerField(default=500, max_length=3),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_tokens', models.BigIntegerField(default=1)),
                ('this_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_profile', to='users.profile')),
                ('with_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_profile', to='users.profile')),
            ],
        ),
    ]
