# Generated by Django 3.1.5 on 2021-04-29 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210428_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 29)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.BigIntegerField(default=500),
        ),
    ]
