# Generated by Django 3.1.6 on 2021-05-04 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210429_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Click Edit Profile to write your bio!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 4)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='No Gender Specified Yet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='No Location Specified Yet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_car_status',
            field=models.CharField(blank=True, default='No Car Status Specified Yet', max_length=255, null=True),
        ),
    ]
