# Generated by Django 3.1.7 on 2021-05-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_post'),
        ('users', '0022_auto_20210505_1751'),
    ]

    operations = [
    ]
